// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjijfiwweppsxcltggna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqaWpmaXd3ZXBwc3hjbHRnZ25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Njk1OTcsImV4cCI6MjA2NDM0NTU5N30.Ekiv9XdhTNHKSPenOKNt1y2IMiljZYz_skMoZXMtX2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);