// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inlqlzejitvedtxsnayw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubHFsemVqaXR2ZWR0eHNuYXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzc3MTksImV4cCI6MjA2MTk1MzcxOX0.g0TTsgvyP8HEzwWJpwyId6PQBih3UiYksUV-oLPuaDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);